package main

import (
	"fmt"
)

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

func main() {
	//jsonStr1 := `{"age": 14,"name": "potter", "child":[1,2,3]}`
	//a := AutoGenerated{}
	//json.Unmarshal([]byte(jsonStr1), &a)
	//aa := a.Child
	//fmt.Println(aa)
	//fmt.Printf("之前 %p \n",a.Child)
	//
	//jsonStr2 := `{"age": 12,"name": "potter", "child":[3,4,5,7]}`
	//json.Unmarshal([]byte(jsonStr2), &a)
	//fmt.Println(aa)
	//fmt.Printf("之后 %p ",a.Child)

	arr := make([]int, 2, 3)

	fmt.Println(arr)
	fmt.Printf("%p \n",arr)
	arr=append(arr,1)
	fmt.Printf("%v \n",arr[2])
}
